name: Setup project
description: Setup project with node pnpm docker-buildx
inputs:
  dependencies:
    description: Install dependencies
    required: false
  docker-buildx:
    description: Install docker buildx
    required: false
runs:
  using: composite
  steps:
    - name: Setup Node.js
      uses: actions/setup-node@39370e3970a6d050c480ffad4ff0ed4d3fdee5af # v4
      with:
        node-version: lts/*

    - name: Setup pnpm
      uses: pnpm/action-setup@v3
      with:
        version: latest

    - name: Get pnpm store path
      shell: bash
      run: |
        echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV

    - name: Cache pnpm store
      uses: actions/cache@6849a6489940f00c2f30c0fb92c6274307ccb58a # v4
      with:
        path: |
          ${{ env.STORE_PATH }}
          node_modules
        key: pnpm-store-${{ runner.os }}-${{ hashFiles('**/pnpm-lock.yaml') }}
        restore-keys: pnpm-store-${{ runner.os }}

    - name: Install npm dependencies
      if: ${{ inputs.dependencies == 'true' }}
      shell: bash
      run: pnpm install --frozen-lockfile

    - name: Install docker buildx
      if: ${{ inputs.docker-buildx == 'true' }}
      uses: docker/setup-buildx-action@c47758b77c9736f4b2ef4073d4d51994fabfe349 # v3
