name: CI

on:
  pull_request_target:
    branches:
      - main
  merge_group:

permissions:
  contents: read
  actions: read
  checks: write
  pull-requests: write

jobs:


  test:
    name: Unit Test Runner
    runs-on: ubuntu-latest
    steps:
      - name: Checkout PR branch
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          repository: ${{ github.event.pull_request.head.repo.full_name }}
      - name: Setup Project
        uses: ./.github/actions/setup
        with:
          dependencies: true
      - name: Add and fetch main branch from original repository
        run: |
          repo="${{github.event.pull_request.base.repo.clone_url}}"
          if [ -z "$repo" ]; then
            repo="https://github.com/${{github.event.repository.full_name}}.git"
          fi
          git remote add upstream "$repo"
          git fetch upstream main
      - name: Run unit test on PR
        if: github.event_name != 'merge_group'
        run: pnpm exec nx affected -t test --base=upstream/main --ci --coverage --coverageReporters=lcov
      - name: Run unit test on Merge Queue
        if: github.event_name == 'merge_group'
        run: pnpm exec nx run-many -t test --ci --coverage --coverageReporters=lcov
      - name: Create github check
        uses: LouisBrunner/checks-action@6b626ffbad7cc56fd58627f774b9067e6118af23 # v2.0.0
        if: always()
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          name: Unit Test Check
          conclusion: ${{  job.status }}

  e2e:
    name: E2E Test Runner
    runs-on: ubuntu-latest
    steps:

      - name: Checkout PR branch
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          repository: ${{ github.event.pull_request.head.repo.full_name }}
      - name: Setup Project
        uses: ./.github/actions/setup
        with:
          dependencies: true
      - name: Add and fetch main branch from original repository
        run: |
          repo="${{github.event.pull_request.base.repo.clone_url}}"
          if [ -z "$repo" ]; then
            repo="https://github.com/${{github.event.repository.full_name}}.git"
          fi
          git remote add upstream "$repo"
          git fetch upstream main
      - name: Run E2E test on PR
        if: github.event_name != 'merge_group'
        run: pnpm exec nx affected -t e2e --base=upstream/main
      - name: Run E2E test on Merge Queue
        if: github.event_name == 'merge_group'
        run: pnpm exec nx run-many -t e2e
      - name: Create github check
        uses: LouisBrunner/checks-action@6b626ffbad7cc56fd58627f774b9067e6118af23 # v2.0.0
        if: always()
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          name: E2E Test Check
          conclusion: ${{  job.status }}



