name: CI

on:
  pull_request_target:
    branches:
      - main
  merge_group:

permissions:
  contents: read
  actions: read
  checks: write

jobs:

  test:
    name: Unit Test Runner
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
        with:
          fetch-depth: 0
      - name: Setup project
        uses: ./.github/actions/setup # local action
        with:
          dependencies: true
      - uses: mansagroup/nrwl-nx-action@v3
        with:
          targets: test
          affected: true
      - uses: LouisBrunner/checks-action@6b626ffbad7cc56fd58627f774b9067e6118af23 # v2.0.0
        if: always()
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          name: Unit Test Check
          conclusion: ${{  job.status }}

  e2e:
    name: E2E Test Runner
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      - name: Setup project
        uses: ./.github/actions/setup # local action
        with:
          dependencies: true
      - uses: mansagroup/nrwl-nx-action@v3
        with:
          targets: e2e
          affected: true
          parallel: 1
      - uses: LouisBrunner/checks-action@6b626ffbad7cc56fd58627f774b9067e6118af23 # v2.0.0
        if: always()
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          name: E2E Test Check
          conclusion: ${{  job.status }}



