name: Release

on:
  push:
    branches:
      - main

permissions:
  pull-requests:  write

jobs:

  release:
    name: Release please
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4

      - name: Release Please
        id: release
        uses: googleapis/release-please-action@7987652d64b4581673a76e33ad5e98e3dd56832f # v4
        with:
          token: ${{ secrets.GH_BOT_TOKEN }}
          config-file: release-config.json
          manifest-file: release-manifest.json
          fork: true
