name: Trunk

on:
  pull_request_target:
    branches:
      - main
  merge_group:

permissions:
  contents: read
  checks: write

jobs:

  trunk-runner:
    name: Trunk Runner
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      - name: Setup project
        uses: ./.github/actions/setup # local action
        with:
          dependencies: true
      - name: Trunk Code Quality
        uses: trunk-io/trunk-action@4d5ecc89b2691705fd08c747c78652d2fc806a94 # v1
        with:
          check-mode: ${{ github.event_name == 'pull_request_target' &&  'pull_request' || 'all' }}
          github-token: ${{ secrets.GH_BOT_TOKEN }}
      - name: Create check on merge group
        uses: LouisBrunner/checks-action@6b626ffbad7cc56fd58627f774b9067e6118af23 # v2.0.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          name: Trunk Check
          conclusion: success
